FROM ubuntu:16.04

ARG AWS_DEFAULT_REGION
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ACCESS_KEY_ID
ARG SNS_TOPIC_ARN

ENV AWS_DEFAULT_REGION ${AWS_DEFAULT_REGION}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV SNS_TOPIC_ARN ${SNS_TOPIC_ARN}

RUN apt-get update && apt-get install -y inotify-tools python-pip
RUN pip install awscli
RUN mkdir /data
COPY filewatcher.sh /usr/local/bin/
CMD /usr/local/bin/filewatcher.sh
