version: '3'
services:
  filewatcher:
    image: "filewatcher:${FILEWATCHER_IMAGE_TAG:-latest}"
    build:
      context: filewatcher
      dockerfile: Dockerfile.filewatcher
      args:
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
        AWS_DEFAULT_REGION: "ap-southeast-2"
        SNS_TOPIC_ARN: "${SNS_TOPIC_ARN}"
  apache:
    image: "apache:${APACHE_IMAGE_TAG:-latest}"
    build:
      context: apache
      dockerfile: Dockerfile.apache
    ports:
      - "8080:80"
